import { v4 as uuidv4 } from "uuid";

interface Transaction {
  id: string;
  type: string;
  amount: number;
  name: string;
  category: string;
  date: string;
  method: string;
  comments: string;
}

export const transactions: Transaction[] = [
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2025-01-03",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1200,
    name: "Office Commute",
    category: "Travel",
    date: "2025-01-15",
    method: "UPI",
    comments: "Monthly bus pass",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2025-01-05",
    method: "Net Banking",
    comments: "January salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2025-01-28",
    method: "Net Banking",
    comments: "January rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 25000,
    name: "New Laptop",
    category: "Shopping",
    date: "2025-01-20",
    method: "Card",
    comments: "Work laptop upgrade",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2025-02-02",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1300,
    name: "Office Commute",
    category: "Travel",
    date: "2025-02-14",
    method: "Card",
    comments: "Monthly train pass",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 15000,
    name: "Freelance Payment",
    category: "Miscellaneous",
    date: "2025-02-10",
    method: "Net Banking",
    comments: "Project payment",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2025-02-27",
    method: "Net Banking",
    comments: "February rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 3000,
    name: "Concert Tickets",
    category: "Entertainment",
    date: "2025-02-18",
    method: "UPI",
    comments: "Live music event",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 11000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2025-03-04",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1400,
    name: "Office Commute",
    category: "Travel",
    date: "2025-03-15",
    method: "UPI",
    comments: "Monthly bus pass",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2025-03-05",
    method: "Net Banking",
    comments: "March salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2025-03-28",
    method: "Net Banking",
    comments: "March rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 20000,
    name: "Flight Tickets",
    category: "Travel",
    date: "2025-03-22",
    method: "Card",
    comments: "Business trip",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2025-04-01",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1500,
    name: "Office Commute",
    category: "Travel",
    date: "2025-04-14",
    method: "Card",
    comments: "Monthly train pass",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2025-04-05",
    method: "Net Banking",
    comments: "April salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2025-04-28",
    method: "Net Banking",
    comments: "April rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 32000,
    name: "Electricity Bill",
    category: "Utilities",
    date: "2025-04-15",
    method: "Net Banking",
    comments: "Quarterly bill",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2025-05-01",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1450,
    name: "Office Commute",
    category: "Travel",
    date: "2025-05-02",
    method: "UPI",
    comments: "Monthly bus pass",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 5000,
    name: "Refund",
    category: "Miscellaneous",
    date: "2025-05-01",
    method: "UPI",
    comments: "Returned item",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 6000,
    name: "Doctor Visit",
    category: "Healthcare",
    date: "2025-05-02",
    method: "Card",
    comments: "Checkup",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 8000,
    name: "Car Insurance",
    category: "Insurance",
    date: "2025-05-02",
    method: "Net Banking",
    comments: "Annual premium",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2024-01-05",
    method: "Net Banking",
    comments: "January salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2024-01-02",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2024-01-28",
    method: "Net Banking",
    comments: "January rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1200,
    name: "Office Commute",
    category: "Travel",
    date: "2024-01-15",
    method: "UPI",
    comments: "Monthly bus pass",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2024-02-05",
    method: "Net Banking",
    comments: "February salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2024-02-03",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2024-02-27",
    method: "Net Banking",
    comments: "February rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 2800,
    name: "Movie Tickets",
    category: "Entertainment",
    date: "2024-02-20",
    method: "Card",
    comments: "Cinema night",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2024-03-05",
    method: "Net Banking",
    comments: "March salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2024-03-01",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2024-03-28",
    method: "Net Banking",
    comments: "March rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 15000,
    name: "Train Tickets",
    category: "Travel",
    date: "2024-03-18",
    method: "UPI",
    comments: "Vacation travel",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2024-04-05",
    method: "Net Banking",
    comments: "April salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2024-04-02",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2024-04-28",
    method: "Net Banking",
    comments: "April rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 30000,
    name: "New Phone",
    category: "Shopping",
    date: "2024-04-10",
    method: "Card",
    comments: "Smartphone upgrade",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2024-05-05",
    method: "Net Banking",
    comments: "May salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2024-05-01",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1300,
    name: "Office Commute",
    category: "Travel",
    date: "2024-05-15",
    method: "UPI",
    comments: "Monthly bus pass",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 7500,
    name: "Health Checkup",
    category: "Healthcare",
    date: "2024-05-20",
    method: "Card",
    comments: "Annual checkup",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2024-06-05",
    method: "Net Banking",
    comments: "June salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2024-06-03",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2024-06-28",
    method: "Net Banking",
    comments: "June rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 28000,
    name: "Water Bill",
    category: "Utilities",
    date: "2024-06-15",
    method: "Net Banking",
    comments: "Quarterly bill",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2024-07-05",
    method: "Net Banking",
    comments: "July salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2024-07-02",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2024-07-28",
    method: "Net Banking",
    comments: "July rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 3200,
    name: "Amusement Park",
    category: "Entertainment",
    date: "2024-07-22",
    method: "UPI",
    comments: "Family outing",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2024-08-05",
    method: "Net Banking",
    comments: "August salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2024-08-01",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2024-08-28",
    method: "Net Banking",
    comments: "August rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1400,
    name: "Office Commute",
    category: "Travel",
    date: "2024-08-15",
    method: "Card",
    comments: "Monthly train pass",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2024-09-05",
    method: "Net Banking",
    comments: "September salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2024-09-03",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2024-09-28",
    method: "Net Banking",
    comments: "September rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 8500,
    name: "Home Insurance",
    category: "Insurance",
    date: "2024-09-10",
    method: "Net Banking",
    comments: "Annual premium",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2024-10-05",
    method: "Net Banking",
    comments: "October salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2024-10-02",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2024-10-28",
    method: "Net Banking",
    comments: "October rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 27000,
    name: "Furniture Purchase",
    category: "Shopping",
    date: "2024-10-12",
    method: "Card",
    comments: "New sofa",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2024-11-05",
    method: "Net Banking",
    comments: "November salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2024-11-01",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2024-11-28",
    method: "Net Banking",
    comments: "November rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1300,
    name: "Office Commute",
    category: "Travel",
    date: "2024-11-15",
    method: "UPI",
    comments: "Monthly bus pass",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2024-12-05",
    method: "Net Banking",
    comments: "December salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2024-12-02",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2024-12-28",
    method: "Net Banking",
    comments: "December rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 3500,
    name: "Holiday Event",
    category: "Entertainment",
    date: "2024-12-20",
    method: "Card",
    comments: "Christmas party",
  },
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2023-01-05",
    method: "Net Banking",
    comments: "January salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2023-01-03",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2023-01-28",
    method: "Net Banking",
    comments: "January rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1100,
    name: "Office Commute",
    category: "Travel",
    date: "2023-01-15",
    method: "UPI",
    comments: "Monthly bus pass",
  },
  // February
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2023-02-05",
    method: "Net Banking",
    comments: "February salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2023-02-02",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2023-02-27",
    method: "Net Banking",
    comments: "February rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 2600,
    name: "Theater Tickets",
    category: "Entertainment",
    date: "2023-02-18",
    method: "Card",
    comments: "Play performance",
  },
  // March
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2023-03-05",
    method: "Net Banking",
    comments: "March salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2023-03-01",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2023-03-28",
    method: "Net Banking",
    comments: "March rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Flight Tickets",
    category: "Travel",
    date: "2023-03-20",
    method: "Card",
    comments: "Family trip",
  },
  // April
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2023-04-05",
    method: "Net Banking",
    comments: "April salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2023-04-02",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2023-04-28",
    method: "Net Banking",
    comments: "April rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 28000,
    name: "TV Purchase",
    category: "Shopping",
    date: "2023-04-12",
    method: "Card",
    comments: "New smart TV",
  },
  // May
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2023-05-05",
    method: "Net Banking",
    comments: "May salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2023-05-01",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1200,
    name: "Office Commute",
    category: "Travel",
    date: "2023-05-15",
    method: "UPI",
    comments: "Monthly bus pass",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 7000,
    name: "Dental Visit",
    category: "Healthcare",
    date: "2023-05-22",
    method: "Card",
    comments: "Checkup",
  },
  // June
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2023-06-05",
    method: "Net Banking",
    comments: "June salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2023-06-03",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2023-06-28",
    method: "Net Banking",
    comments: "June rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 30000,
    name: "Gas Bill",
    category: "Utilities",
    date: "2023-06-15",
    method: "Net Banking",
    comments: "Quarterly bill",
  },
  // July
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2023-07-05",
    method: "Net Banking",
    comments: "July salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2023-07-02",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2023-07-28",
    method: "Net Banking",
    comments: "July rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 3000,
    name: "Concert Tickets",
    category: "Entertainment",
    date: "2023-07-20",
    method: "UPI",
    comments: "Music festival",
  },
  // August
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2023-08-05",
    method: "Net Banking",
    comments: "August salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2023-08-01",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2023-08-28",
    method: "Net Banking",
    comments: "August rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1300,
    name: "Office Commute",
    category: "Travel",
    date: "2023-08-15",
    method: "Card",
    comments: "Monthly train pass",
  },
  // September
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2023-09-05",
    method: "Net Banking",
    comments: "September salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2023-09-03",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2023-09-28",
    method: "Net Banking",
    comments: "September rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 8000,
    name: "Car Insurance",
    category: "Insurance",
    date: "2023-09-10",
    method: "Net Banking",
    comments: "Annual premium",
  },
  // October
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2023-10-05",
    method: "Net Banking",
    comments: "October salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2023-10-02",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2023-10-28",
    method: "Net Banking",
    comments: "October rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 26000,
    name: "Laptop Purchase",
    category: "Shopping",
    date: "2023-10-15",
    method: "Card",
    comments: "New work laptop",
  },
  // November
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2023-11-05",
    method: "Net Banking",
    comments: "November salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 10000,
    name: "Grocery Shopping",
    category: "Food",
    date: "2023-11-01",
    method: "Card",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2023-11-28",
    method: "Net Banking",
    comments: "November rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 1200,
    name: "Office Commute",
    category: "Travel",
    date: "2023-11-15",
    method: "UPI",
    comments: "Monthly bus pass",
  },
  // December
  {
    id: uuidv4(),
    type: "Credit",
    amount: 200000,
    name: "Salary",
    category: "Miscellaneous",
    date: "2023-12-05",
    method: "Net Banking",
    comments: "December salary",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 9500,
    name: "Grocery Shopping",
    category: "Food",
    date: "2023-12-02",
    method: "UPI",
    comments: "Monthly groceries",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 18000,
    name: "Apartment Rent",
    category: "Rent",
    date: "2023-12-28",
    method: "Net Banking",
    comments: "December rent",
  },
  {
    id: uuidv4(),
    type: "Debit",
    amount: 3400,
    name: "New Year Party",
    category: "Entertainment",
    date: "2023-12-22",
    method: "Card",
    comments: "Celebration event",
  },
];
export const yearOptions = Array.from({ length: 2025 - 2000 + 1 }, (_, i) =>
  (2000 + i).toString()
); // [2000, 2001, ..., 2025]
export const monthOptions = [
  "All",
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];
export const categoryOptions = [
  "All",
  "Food",
  "Travel",
  "Entertainment",
  "Shopping",
  "Healthcare",
  "Education",
  "Rent",
  "Utilities",
  "Insurance",
  "Miscellaneous",
];
export const typeOptions = ["All", "Credit", "Debit"];
export const methodOptions = ["All", "UPI", "Card", "Cash", "Net Banking"];

export const monthToValue = (month: string, year: string) =>
  month === "All"
    ? "All"
    : `${monthOptions.indexOf(month) < 10 ? "0" : ""}${monthOptions.indexOf(
        month
      )}`;
export const valueToMonth = (value: string) =>
  value === "All" ? "All" : monthOptions[parseInt(value)];

export const monthOptionsLine = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];
export const monthToValueLine = (month: string) =>
  `${monthOptions.indexOf(month) + 1 < 10 ? "0" : ""}${
    monthOptions.indexOf(month) + 1
  }`;
export const valueToMonthLine = (value: string) =>
  monthOptions[parseInt(value) - 1];
